server:
  port: '8080'
spring:
  application:
    name: tdei-auth
    secret: "${SPRING_APPLICATION_SECRET}"
    secret-ttl: "${SPRING_APPLICATION_SECRET_TTL}"
  config:
    import: optional:developer-local-properties.yaml
  datasource:
    username: "${SPRING_DATASOURCE_USERNAME}"
    url: "${SPRING_DATASOURCE_URL}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: Authentication/Authorization API, this API is responsible any service related to the authentication and authorization of the user like authenticating the users, issuing the access/refresh tokens, api keys, validating the permissions for the users. This service will be exposed on Azure intranet and can be consumed by Azure intranet applications/services.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI API
  version: v0.1
Keycloak-client-endpoints:
  base-url: "${KEYCLOAK_CLIENT_ENDPOINTS_BASE_URL}"
keycloak:
  auth-server-url: "${KEYCLOAK_AUTH_SERVER_URL}"
  realm: tdei
  enabled: true
  bearer-only: true
  resource: tdei-gateway
  credentials:
    secret:
  use-resource-role-mappings: true
logging:
  level:
    org.keycloak: DEBUG
    root: info
    web: info