spring:
  application:
    name: tdei-auth
  config:
    import: optional:developer-local-properties.yaml
  port: '8080'
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: Authentication/Authorization API, this API is responsible any service related to the authentication and authorization of the user like authenticating the users, issuing the access/refresh tokens, api keys, validating the permissions for the users. This service will be exposed on Azure intranet and can be consumed by Azure intranet applications/services.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI API
  version: v0.1
Keycloak-client-endpoints:
  user-url: https://tdei-keycloak.azurewebsites.net/realms/tdei/protocol/openid-connect/userinfo
keycloak:
  auth-server-url: https://tdei-keycloak.azurewebsites.net
  realm: tdei
  enabled: true
  bearer-only: true
  resource: tdei-gateway
  credentials:
    secret:
  use-resource-role-mappings: true
logging:
  level:
    org.keycloak: DEBUG
    root: info
    web: info