spring:
  application:
    name: tdei-auth
server:
  port: '8081'
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: Authentication & Authorization service.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI API
  version: 0.0.1
Keycloak-client-endpoints:
  user-url: https://tdei-keycloak.azurewebsites.net/realms/tdei/protocol/openid-connect/userinfo
keycloak:
  auth-server-url: https://tdei-keycloak.azurewebsites.net
  realm: tdei
  enabled: true
  bearer-only: true
  resource: tdei-gateway
  credentials:
    secret: A71N884x3HbU2g4KKIsww8pt5VXxxNNH
  use-resource-role-mappings: true
logging:
  level:
    org.keycloak: DEBUG
    root: info
    web: info