
on:
  pull_request:
    branches: [github-workflow-poc-dev]
    types:
      - closed
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t tdeidocker.azurecr.io/auth-n-z:${{ github.sha }}
        docker push tdeidocker.azurecr.io/auth-n-z:${{ github.sha }} 






