
on:
  pull_request:
    branches: [github-workflow-poc-dev]
    types:
      - closed
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        ls -l 
        docker build . -t tdeidocker.azurecr.io/auth-n-z:${{ github.sha }}
        docker push tdeidocker.azurecr.io/auth-n-z:${{ github.sha }} 






